# Generated by Django 6.0 on 2026-09-25 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0007_subscriber_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('device', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], default='desktop', max_length=20)),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('scroll_depth', models.IntegerField(default=0, help_text='Porcentaje scrolleado (0-100)')),
                ('time_spent', models.IntegerField(default=0, help_text='Segundos en la página')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['path', '-timestamp'], name='analytics_p_path_89b690_idx'), models.Index(fields=['session_id', '-timestamp'], name='analytics_p_session_57683f_idx'), models.Index(fields=['country', '-timestamp'], name='analytics_p_country_596e27_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_today', models.IntegerField(default=0)),
                ('views_7d', models.IntegerField(default=0)),
                ('views_30d', models.IntegerField(default=0)),
                ('views_all_time', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0, help_text='0-100%')),
                ('avg_scroll_depth', models.FloatField(default=0.0)),
                ('avg_time_spent', models.IntegerField(default=0, help_text='Segundos promedio')),
                ('unique_visitors_7d', models.IntegerField(default=0)),
                ('trending_score', models.FloatField(default=0.0, help_text='Score para trending (7d)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='blog.post')),
            ],
            options={
                'verbose_name': 'Post Analytics',
                'verbose_name_plural': 'Post Analytics',
                'ordering': ['-views_today'],
            },
        ),
        migrations.CreateModel(
            name='RelatedPostsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_posts_cache', to='blog.post')),
                ('related_posts', models.ManyToManyField(blank=True, help_text='Posts relacionados por tags compartidos', related_name='related_by_cache', to='blog.post')),
            ],
            options={
                'verbose_name': 'Related Posts Cache',
                'verbose_name_plural': 'Related Posts Cache',
            },
        ),
        migrations.CreateModel(
            name='SessionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('device', models.CharField(default='desktop', max_length=20)),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('first_page', models.CharField(max_length=500)),
                ('last_page', models.CharField(max_length=500)),
                ('page_count', models.IntegerField(default=1)),
                ('total_duration', models.IntegerField(default=0, help_text='Segundos totales')),
                ('is_bounce', models.BooleanField(default=True, help_text='True si solo visitó 1 página')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['country', '-created_at'], name='analytics_s_country_b03bde_idx'), models.Index(fields=['device', '-created_at'], name='analytics_s_device_47d19e_idx')],
            },
        ),
    ]
