# Generated by Django 6.0 on 2026-09-29 20:56

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_CHANNELS = [
    ('linkedin', 'LinkedIn', 'Enlace de la web en el perfil de LinkedIn'),
    ('firma', 'Firma de correo', 'Enlace en la firma del email'),
    ('cv', 'CV en PDF', 'Enlace dentro del CV descargable'),
]


def create_channels(apps, schema_editor):
    Channel = apps.get_model('analytics', 'Channel')
    for code, name, notes in DEFAULT_CHANNELS:
        Channel.objects.get_or_create(code=code, defaults={'name': name, 'notes': notes})


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_anonymize_stored_visits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Aparece en la URL: https://hernandezpalo.es/?src=codigo', max_length=40, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Ej: LinkedIn, Firma de correo, CV en PDF', max_length=100, verbose_name='Nombre')),
                ('notes', models.CharField(blank=True, default='', max_length=250, verbose_name='Dónde está puesto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cv_download', 'Descarga del CV'), ('contact_submit', 'Mensaje de contacto'), ('newsletter_subscribe', 'Suscripción a la newsletter'), ('outbound_click', 'Clic a web externa'), ('case_open', 'Caso de éxito abierto'), ('filter_use', 'Filtro de proyectos')], db_index=True, max_length=30)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('visitor_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('asn', models.PositiveIntegerField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, default='', max_length=150)),
                ('network_type', models.CharField(choices=[('business', 'Empresa u organización'), ('corporate_proxy', 'Empresa (vía proxy corporativo)'), ('education', 'Universidad o centro educativo'), ('government', 'Administración pública'), ('isp', 'Particular (operadora)'), ('mobile', 'Particular (red móvil)'), ('hosting', 'Centro de datos / bots'), ('unknown', 'Desconocida')], default='unknown', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NetworkLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.PositiveIntegerField(unique=True, verbose_name='ASN')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre a mostrar')),
                ('network_type', models.CharField(choices=[('business', 'Empresa u organización'), ('corporate_proxy', 'Empresa (vía proxy corporativo)'), ('education', 'Universidad o centro educativo'), ('government', 'Administración pública'), ('isp', 'Particular (operadora)'), ('mobile', 'Particular (red móvil)'), ('hosting', 'Centro de datos / bots'), ('unknown', 'Desconocida')], max_length=20, verbose_name='Tipo')),
                ('notes', models.CharField(blank=True, default='', max_length=250, verbose_name='Notas')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etiqueta de red',
                'verbose_name_plural': 'Etiquetas de red',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pageview',
            name='asn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='network_type',
            field=models.CharField(choices=[('business', 'Empresa u organización'), ('corporate_proxy', 'Empresa (vía proxy corporativo)'), ('education', 'Universidad o centro educativo'), ('government', 'Administración pública'), ('isp', 'Particular (operadora)'), ('mobile', 'Particular (red móvil)'), ('hosting', 'Centro de datos / bots'), ('unknown', 'Desconocida')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='pageview',
            name='organization',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pageview',
            name='pageview_id',
            field=models.UUIDField(blank=True, editable=False, help_text='Enlaza las métricas de lectura enviadas por el navegador', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='referrer_domain',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pageview',
            name='source',
            field=models.CharField(choices=[('channel', 'Canal propio (?src=)'), ('campaign', 'Campaña (UTM)'), ('email', 'Correo (webmail)'), ('social', 'Red social'), ('search', 'Buscador'), ('referral', 'Otra web'), ('internal', 'Navegación interna'), ('direct', 'Directo')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='pageview',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pageview',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pageview',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pageview',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador anónimo mensual (no reversible)', max_length=32),
        ),
        migrations.AddField(
            model_name='sessiontracker',
            name='network_type',
            field=models.CharField(choices=[('business', 'Empresa u organización'), ('corporate_proxy', 'Empresa (vía proxy corporativo)'), ('education', 'Universidad o centro educativo'), ('government', 'Administración pública'), ('isp', 'Particular (operadora)'), ('mobile', 'Particular (red móvil)'), ('hosting', 'Centro de datos / bots'), ('unknown', 'Desconocida')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='sessiontracker',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='sessiontracker',
            name='source',
            field=models.CharField(choices=[('channel', 'Canal propio (?src=)'), ('campaign', 'Campaña (UTM)'), ('email', 'Correo (webmail)'), ('social', 'Red social'), ('search', 'Buscador'), ('referral', 'Otra web'), ('internal', 'Navegación interna'), ('direct', 'Directo')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='sessiontracker',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='pageview',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pageviews', to='analytics.channel'),
        ),
        migrations.AddField(
            model_name='sessiontracker',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='analytics.channel'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['visitor_id', '-timestamp'], name='analytics_p_visitor_797ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['network_type', '-timestamp'], name='analytics_p_network_bd7f6a_idx'),
        ),
        migrations.AddField(
            model_name='event',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analytics.channel'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['kind', '-timestamp'], name='analytics_e_kind_779437_idx'),
        ),
        migrations.RunPython(create_channels, migrations.RunPython.noop),
    ]
