# Generated by Django 6.0.1 on 2026-01-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Productos'},
        ),
    ]
