-- Generated by scripts/generate_documentum_sql.py (sqlite dialect)
BEGIN;
INSERT OR IGNORE INTO documentum_category (name, slug, description, icon, "order", is_visible, created_at, updated_at) VALUES ('General', 'general', 'Imported category General', 'fa-book', 0, 1, now(), now());
INSERT OR IGNORE INTO documentum_category (name, slug, description, icon, "order", is_visible, created_at, updated_at) VALUES ('app', 'app', 'Imported category app', 'fa-book', 0, 1, now(), now());

INSERT INTO documentum_document (title, slug, category_id, content_markdown, content_html, status, last_revision, stack_version, meta_description, meta_keywords, created_at, updated_at) VALUES ('CHANGELOG', 'changelog', (SELECT id FROM documentum_category WHERE slug='general'), '# CHANGELOG

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

---

## [2.2.5] - 2026-01-30

### 🎯 Dynamic Metrics & Admin Stability

This release introduces a dynamic metrics system for the landing page and fixes critical admin interface issues that were causing 500 errors in production.

#### Added
- ✨ **Dynamic Metrics System**: New `Metric` model for managing impact metrics from Django Admin.
    - Fields: `value`, `prefix`, `suffix`, `title`, `description`, `is_visible`, `order`
    - Custom admin interface with inline value preview and drag-to-reorder functionality
    - Automatic percentage calculation for progress ring animations
    - Template refactored to use `{% for metric in metrics %}` loop
- 🎨 **Accessibility Improvements**: Enhanced color contrast in Education Grid cards.
    - Background: Lightened to `#1e1e1e` for better visibility
    - Dates: Updated to luminous pink `#FF4081` (WCAG AA compliant)
    - Text: Brightened to `#e0e0e0` and `#d1d1d1` for AAA compliance

#### Fixed
- 🐛 **SkillAdmin**: Added missing `list_display_links = (''name'',)` to prevent Django validation error when using `list_editable`
- 🐛 **ProjectAdmin**: Fixed `get_description_preview()` method to safely handle new objects (before first save) and properly render HTML with `mark_safe()`
- 🐛 **Experience Model**: Removed redundant `null=True` from `resumen` CKEditor5 field (conflicted with `default=""`)

#### Database
- 📊 **Migrations**: 
    - `0013_metric_*`: Created Metric model and related fields
    - `0014_alter_experience_resumen`: Fixed CKEditor5 field configuration

#### Verification
- ✅ **System Check**: `manage.py check` passed with no issues
- ✅ **Admin Interface**: All models now editable without 500 errors

---

## [2.2.4] - 2026-01-30

### 🚀 Performance Boost & Modernization (No-jQuery)

Major performance milestone focusing on loading speed and modernization of the frontend stack by removing legacy dependencies.

#### Performance
- ⚡ **Removed jQuery**: Completely removed `jquery-2.1.3.min.js` and all dependent plugins (OwlCarousel, Masonry, MagnificPopup) from the Landing Page.
- 📉 **Asset Reduction**: Saved **~150KB** of blocking JS/CSS scripts.
- ⚡ **HTML Minification**: Implemented `django-htmlmin` middleware to compress HTML output in production (DEBUG=False).
- 🚀 **Critical CSS**: Optimized `no-js` class handling with an inline script in `<head>` to prevent Flash of Unstyled Content (FOUC).

#### Refactored (Vanilla JS)
- 🏗️ **`main.js`**: Rewritten entirely in ES6+ Vanilla JavaScript.
    - **Navigation**: Lightweight class toggling.
    - **ScrollSpy**: Implemented using `IntersectionObserver` API (more performant than scroll listeners).
    - **Smooth Scroll**: Replaced custom logic with native `scrollIntoView`.
    - **Contact Form**: Replaced `jquery-validate` + AJAX with modern `fetch()` API.

#### Changed
- 🎨 **Typography**: Replaced JS-based `FitText` plugin with CSS `clamp()` for responsive headlines (Zero-JS approach).
- 🏗️ **Stack Definition**: Explicit separation of Public Stack (Vanilla JS + Kards CSS) vs Private Stack (Bootstrap 5).

#### Verification
- ✅ **System Check**: `manage.py check` passed.
- ✅ **Static Analysis**: Confirmed zero references to `$` or `jQuery` in public assets.

---

## [2.2.3] - 2026-01-25

### 🧹 Code Integrity & Performance Optimization

This release focuses on "Clean Code" principles, separating logic from presentation, and restoring critical SEO components after a major cleanup.

#### Refactoring & Automation (New)
- 🏗️ **Template Architecture**: Major refactor moving all templates to a centralized `app/templates` structure with clear separation between `landing` (public) and `private` (dashboard) areas.
- ⚙️ **Automated Verification**: Implemented a robust `verify_urls` management command and a Git pre-commit hook to prevent regression by verifying all critical URLs before every commit.
- 🚀 **LCP Optimization**: Fixed critical CSS image path causing 404s and delays. Added explicit preload for Hero background image to improve Largest Contentful Paint.
- 🗑️ **Cleanup**: Removed deprecated template directories and effectively centralized the frontend architecture.

#### Added
- 🧼 **Separation of Concerns**: Moved all inline CSS and `<style>` blocks from HTML templates (`base.html`, `resume.html`, `post.html`) to external `components.css`.
- 🛡️ **SEO Shield**: Restored and validated all meta-tags, Open Graph (LinkedIn/Twitter) integration, and JSON-LD structured data for better search engine ranking.
- 🎨 **Visual Rhythm**: Applied a soft gray background (`#f7f7f7`) to the "Mi Historia" section to create a cleaner visual transition between blocks.
- 🤖 **CI/CD Local**: Added `.git/hooks/pre-commit` for local quality assurance.

#### Changed
- 📐 **Grid Robustness**: Updated `.education-grid` and `.blog-grid` to ensure a consistent 3-column layout on desktop, improving responsiveness on 1024px screens.
- 📏 **Enhanced Spacing**: Increased vertical margin above the "Explorar el Blog Completo" button to **15rem** for better visual breathing room.
- 🔄 **Cache Busting**: Incremented static file versioning (v1.6) to ensure all users receive the latest visual updates immediately.
- 📂 **Project Structure**: Centralized templates in `app/templates/` (replacing `app/landing/templates`).

#### Fixed
- 🐛 **Dynamic Date Rendering**: Fixed a critical template logic error where raw Django tags were visible in the Education cards. Now correctly displays "Year - Actualidad".
- 🧩 **Template Syntax**: Repaired broken curly braces and malformed block tags in `base.html` that were causing performance lag.
- 🔗 **URL NameSpace Conflict**: Resolved Django warning `urls.W005` by removing redundant inclusion of `landing.urls` in the core configuration.
- 🔧 **Login View**: Corrected `LoginView` template path to point to the new location.
- 🐛 **Gym Namespace**: Fixed URL namespace issue in gym product list template.

---

## [2.2.2] - 2026-01-23

### 📰 Safari Compatibility & UI Polishing

This release focuses on cross-browser compatibility (especially for Safari/iOS) and UI refinements across the landing and blog sections.

#### Fixed
- 📱 **Safari Mobile Compatibility**: Resolved invisible background issue in the Intro section on iOS. Added Webkit-specific flexbox prefixes to ensure Education cards maintain their layout in Safari.
- 🌓 **Blog Dark Mode**: Implemented a higher-contrast dark theme for the blog (list and detail) specifically optimized for Safari Mac, ensuring readability when system dark mode is active.
- 🐛 **Template Syntax**: Fixed a critical syntax error in `base.html` that was affecting CSS parsing.

#### Changed
- 📋 **Blog Section Limit**: Restricted the number of featured blog posts on the landing page to 3 for a cleaner, balanced 3-column layout.
- 🖼️ **Hero Optimization**: Set Intro background to `cover` and centered position for a better visual experience on mobile devices.

---

## [2.2.0] - 2026-01-23

### ✨ UI/UX Redesign & Layout Optimization

This release introduces a major aesthetic overhaul of key landing page sections and fixes several long-standing layout and template rendering issues.

#### Added
- 🎨 **New Education Design**: Premium dark-themed, card-based layout for "Educación y Certificaciones" with modern hover effects and radial gradients.
- 🖼️ **Enhanced Portfolio Cards**: Redesigned project cards with explicit "Ver Proyecto" buttons, high-contrast badges, and smooth image zoom transitions.
- 📐 **New Centering System**: Created `app/landing/static/landing/css/centering_fixes.css` to unify row widths and centering across all sections.

#### Changed
- 📏 **Blog List Optimization**: Increased content area width to 1300px (75% column) for better readability on large screens.
- 📨 **Contact Form Overhaul**: Standardized form width to 1200px, aligning perfectly with section headers.
- 📱 **Mobile Responsiveness**: Re-optimized card stacking and padding for small devices across redesigned sections.

#### Fixed
- 🐛 **Template Tag Brokenness**: Joined split Django template tags (`{{ ... }}`) in `resume.html`, `portfolio.html`, and `base.html` that were causing hardcoded-like text rendering in the UI.
- 📐 **Education Grid Alignment**: Fixed inconsistent card heights and widths in the formation section using flexbox.
- 🔲 **Layout Mismatches**: Resolved 100px width difference between section intros and their content blocks.

#### Technical
- 🏗️ Modernized `components.css` with cleaner, class-based styles instead of inline template styling.
- 🧹 Removed redundant and conflicting layout constraints.

---

## [2.1.0] - 2026-01-18

### 🎯 Project Cleanup & Code Quality

This release focuses on comprehensive code cleanup, removing unused templates, CSS classes, and improving overall codebase maintainability. No breaking changes. 100% backwards compatible.

#### Added
- ✨ Comprehensive documentation structure (`docs/changelog/`)
- 📊 Code audit reports and metrics
- 🔍 Automated cleanup analysis tools
- 📋 Checklist for future audits
- 🏗️ Professional documentation guidelines

#### Removed
- ❌ **HTML Templates** (2 files):
  - `app/gym/templates/product_table_htmx.html` - Unused HTMX template
  - `app/gym/templates/product_table_partial.html` - Unused partial template
  
- ❌ **CSS Classes** (105 unused selectors):
  - **Grid System Legacy** (23 classes): `.col-*`, `.mob-*`, `.tab-*` 
    - Replaced by Bootstrap 5 native grid system
  - **Typography** (26 classes): `.h01-.h06`, `.percent5-.percent100`
    - No references in current templates
  - **Components** (56 classes): `.folio-*`, `.services-*`, `.pagination-*`, etc.
    - Deprecated from previous template version

- 📝 **CSS Optimization**:
  - `app/landing/static/landing/css/base.css`: -23 lines (-2.6%)
  - `app/landing/static/landing/css/main.css`: -82 lines (-3.7%)
  - **Total CSS reduction: -105 lines (-3.2%)**

#### Changed
- 🔧 **Python Views**:
  - `app/landing/views.py`: `profile()` function now redirects to `private_area`
    - Was attempting to render non-existent `landing/profile.html`
    - Now uses proper redirect pattern

#### Fixed
- 🐛 Broken template reference in `landing/views.py:32`
- 🔗 Fixed orphaned template references
- ✅ Verified all Django URLs resolve correctly

#### Security
- ✅ No security regressions
- ✅ All imports validated
- ✅ No new vulnerabilities introduced

#### Performance
- ⚡ CSS file size reduced by 3.2% (~105 lines)
- ⚡ Reduced browser parsing overhead
- ⚡ Cleaner codebase = faster development

#### Testing
- ✅ `python manage.py check` - **PASS**
- ✅ All templates render correctly
- ✅ Admin interface fully functional
- ✅ No console errors in browser
- ✅ Responsive design verified
- ✅ All URLs working as expected
- ✅ Forms (contact, login) functional
- ✅ Static files serving correctly

#### Documentation
- 📖 [INDICE_LIMPIEZA.md](changelog/INDICE_LIMPIEZA.md) - Index of cleanup documentation
- 📖 [LIMPIEZA_HTML.md](changelog/LIMPIEZA_HTML.md) - HTML template cleanup details
- 📖 [LIMPIEZA_CSS_JS.md](changelog/LIMPIEZA_CSS_JS.md) - CSS classes analysis
- 📖 [LIMPIEZA_RESUMEN.txt](changelog/LIMPIEZA_RESUMEN.txt) - Executive summary
- 📖 [INFORME_TECNICO_LIMPIEZA.md](changelog/INFORME_TECNICO_LIMPIEZA.md) - Technical report
- 📖 [CHECKLIST_AUDITORIA.md](changelog/CHECKLIST_AUDITORIA.md) - Audit checklist

#### Migration Guide
No migration needed. This release is **100% backwards compatible**.

Simply pull the latest changes and verify locally:
```bash
git pull
python manage.py check
python manage.py runserver
```

#### Known Issues
- None identified

#### Notes
- Code cleanup focused on proven non-usage
- All removed code had zero references in codebase
- Conservative approach: high-confidence removals only
- Recommendation: Next review in 30 days

---

## [2.0.0] - 2026-01-18

### 🚀 Architectural Review & Code Improvements

Major architectural review implementing modern Django best practices.

#### Added
- ✨ Modularized Django settings (`settings/base.py`, `dev.py`, `prod.py`, `test.py`)
- 📝 Comprehensive logging configuration with rotating file handlers
- 🔍 Type hints across all views (Python 3.10+ compatible)
- ✅ Model validation with `clean()` methods
- 🎨 Enhanced Django admin interface with custom displays
- 🏷️ URL namespaces (gym, blog, prompts)
- 📊 Optimized context processors with caching
- 🔒 Security improvements (CSRF, HSTS, SSL redirect in production)

#### Fixed
- 🐛 Missing imports in `blog/models.py` (strip_tags, Truncator)
- 🐛 `__str__()` methods added to 8 models
- 🐛 Logging infrastructure (print → logger)
- 🐛 Database query optimization (prefetch_related, caching)
- 🐛 Form validation improvements

#### Performance
- ⚡ Context processors now cached (1-hour TTL)
- ⚡ Database queries optimized with prefetch_related
- ⚡ Better logging configuration for production

---

## [1.0.0] - 2025-12-21

### 🎉 Initial Release

Portfolio Django application with:
- Landing page with portfolio showcase
- Blog functionality with categories
- Gym/Products management
- Private user area with prompts
- Admin interface customization
- Bootstrap 5 responsive design

---

## Future Improvements (Roadmap)

### v2.2.0 (Planned)
- [ ] Migrate jQuery to vanilla JavaScript (remove jquery-2.1.3.min.js)
- [ ] Self-host fonts for better performance
- [ ] Minify CSS for production
- [ ] Implement critical CSS
- [ ] Add pytest test suite

### v2.3.0 (Planned)
- [ ] Migrate to Tailwind CSS (optional)
- [ ] Add dark mode support
- [ ] Implement service worker (PWA)
- [ ] Add Google Analytics integration

### v3.0.0 (Planned)
- [ ] Django upgrade to 7.0+
- [ ] Python 3.13+ support
- [ ] Full TypeScript migration (if frontend needed)
- [ ] API first architecture (DRF)

---

## How to Contribute

### Reporting Issues
1. Describe what went wrong
2. Describe what you expected
3. Include steps to reproduce
4. Check existing issues first

### Pull Requests
1. Create feature branch from `main`
2. Make your changes
3. Add/update documentation
4. Test locally: `python manage.py check`
5. Submit PR with clear description

### Code Quality Standards
- ✅ Type hints for all functions
- ✅ Docstrings for complex logic
- ✅ `python manage.py check` must pass
- ✅ No console errors
- ✅ Backwards compatible (or versioned)

---

## Release Notes

### Support
- **Python**: 3.12+
- **Django**: 6.0+
- **Database**: PostgreSQL (Supabase) / SQLite (dev)
- **Hosting**: Render.com

### Security
For security issues, email to: [contact info] instead of creating public issues.

---

## Maintenance Status

| Version | Status | Until |
|---------|--------|-------|
| 2.1.x | Active | 2026-06-18 |
| 2.0.x | Maintenance | 2026-04-18 |
| 1.0.x | Deprecated | 2026-02-18 |

---

## Archive

All historical releases and their documentation are available in `docs/changelog/`

', '', 'published', now(), '', '# CHANGELOG', '', now(), now()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO documentum_documentversion (document_id, content_markdown, created_at, changed_by, change_summary) VALUES ((SELECT id FROM documentum_document WHERE slug='changelog'), '# CHANGELOG

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

---

## [2.2.5] - 2026-01-30

### 🎯 Dynamic Metrics & Admin Stability

This release introduces a dynamic metrics system for the landing page and fixes critical admin interface issues that were causing 500 errors in production.

#### Added
- ✨ **Dynamic Metrics System**: New `Metric` model for managing impact metrics from Django Admin.
    - Fields: `value`, `prefix`, `suffix`, `title`, `description`, `is_visible`, `order`
    - Custom admin interface with inline value preview and drag-to-reorder functionality
    - Automatic percentage calculation for progress ring animations
    - Template refactored to use `{% for metric in metrics %}` loop
- 🎨 **Accessibility Improvements**: Enhanced color contrast in Education Grid cards.
    - Background: Lightened to `#1e1e1e` for better visibility
    - Dates: Updated to luminous pink `#FF4081` (WCAG AA compliant)
    - Text: Brightened to `#e0e0e0` and `#d1d1d1` for AAA compliance

#### Fixed
- 🐛 **SkillAdmin**: Added missing `list_display_links = (''name'',)` to prevent Django validation error when using `list_editable`
- 🐛 **ProjectAdmin**: Fixed `get_description_preview()` method to safely handle new objects (before first save) and properly render HTML with `mark_safe()`
- 🐛 **Experience Model**: Removed redundant `null=True` from `resumen` CKEditor5 field (conflicted with `default=""`)

#### Database
- 📊 **Migrations**: 
    - `0013_metric_*`: Created Metric model and related fields
    - `0014_alter_experience_resumen`: Fixed CKEditor5 field configuration

#### Verification
- ✅ **System Check**: `manage.py check` passed with no issues
- ✅ **Admin Interface**: All models now editable without 500 errors

---

## [2.2.4] - 2026-01-30

### 🚀 Performance Boost & Modernization (No-jQuery)

Major performance milestone focusing on loading speed and modernization of the frontend stack by removing legacy dependencies.

#### Performance
- ⚡ **Removed jQuery**: Completely removed `jquery-2.1.3.min.js` and all dependent plugins (OwlCarousel, Masonry, MagnificPopup) from the Landing Page.
- 📉 **Asset Reduction**: Saved **~150KB** of blocking JS/CSS scripts.
- ⚡ **HTML Minification**: Implemented `django-htmlmin` middleware to compress HTML output in production (DEBUG=False).
- 🚀 **Critical CSS**: Optimized `no-js` class handling with an inline script in `<head>` to prevent Flash of Unstyled Content (FOUC).

#### Refactored (Vanilla JS)
- 🏗️ **`main.js`**: Rewritten entirely in ES6+ Vanilla JavaScript.
    - **Navigation**: Lightweight class toggling.
    - **ScrollSpy**: Implemented using `IntersectionObserver` API (more performant than scroll listeners).
    - **Smooth Scroll**: Replaced custom logic with native `scrollIntoView`.
    - **Contact Form**: Replaced `jquery-validate` + AJAX with modern `fetch()` API.

#### Changed
- 🎨 **Typography**: Replaced JS-based `FitText` plugin with CSS `clamp()` for responsive headlines (Zero-JS approach).
- 🏗️ **Stack Definition**: Explicit separation of Public Stack (Vanilla JS + Kards CSS) vs Private Stack (Bootstrap 5).

#### Verification
- ✅ **System Check**: `manage.py check` passed.
- ✅ **Static Analysis**: Confirmed zero references to `$` or `jQuery` in public assets.

---

## [2.2.3] - 2026-01-25

### 🧹 Code Integrity & Performance Optimization

This release focuses on "Clean Code" principles, separating logic from presentation, and restoring critical SEO components after a major cleanup.

#### Refactoring & Automation (New)
- 🏗️ **Template Architecture**: Major refactor moving all templates to a centralized `app/templates` structure with clear separation between `landing` (public) and `private` (dashboard) areas.
- ⚙️ **Automated Verification**: Implemented a robust `verify_urls` management command and a Git pre-commit hook to prevent regression by verifying all critical URLs before every commit.
- 🚀 **LCP Optimization**: Fixed critical CSS image path causing 404s and delays. Added explicit preload for Hero background image to improve Largest Contentful Paint.
- 🗑️ **Cleanup**: Removed deprecated template directories and effectively centralized the frontend architecture.

#### Added
- 🧼 **Separation of Concerns**: Moved all inline CSS and `<style>` blocks from HTML templates (`base.html`, `resume.html`, `post.html`) to external `components.css`.
- 🛡️ **SEO Shield**: Restored and validated all meta-tags, Open Graph (LinkedIn/Twitter) integration, and JSON-LD structured data for better search engine ranking.
- 🎨 **Visual Rhythm**: Applied a soft gray background (`#f7f7f7`) to the "Mi Historia" section to create a cleaner visual transition between blocks.
- 🤖 **CI/CD Local**: Added `.git/hooks/pre-commit` for local quality assurance.

#### Changed
- 📐 **Grid Robustness**: Updated `.education-grid` and `.blog-grid` to ensure a consistent 3-column layout on desktop, improving responsiveness on 1024px screens.
- 📏 **Enhanced Spacing**: Increased vertical margin above the "Explorar el Blog Completo" button to **15rem** for better visual breathing room.
- 🔄 **Cache Busting**: Incremented static file versioning (v1.6) to ensure all users receive the latest visual updates immediately.
- 📂 **Project Structure**: Centralized templates in `app/templates/` (replacing `app/landing/templates`).

#### Fixed
- 🐛 **Dynamic Date Rendering**: Fixed a critical template logic error where raw Django tags were visible in the Education cards. Now correctly displays "Year - Actualidad".
- 🧩 **Template Syntax**: Repaired broken curly braces and malformed block tags in `base.html` that were causing performance lag.
- 🔗 **URL NameSpace Conflict**: Resolved Django warning `urls.W005` by removing redundant inclusion of `landing.urls` in the core configuration.
- 🔧 **Login View**: Corrected `LoginView` template path to point to the new location.
- 🐛 **Gym Namespace**: Fixed URL namespace issue in gym product list template.

---

## [2.2.2] - 2026-01-23

### 📰 Safari Compatibility & UI Polishing

This release focuses on cross-browser compatibility (especially for Safari/iOS) and UI refinements across the landing and blog sections.

#### Fixed
- 📱 **Safari Mobile Compatibility**: Resolved invisible background issue in the Intro section on iOS. Added Webkit-specific flexbox prefixes to ensure Education cards maintain their layout in Safari.
- 🌓 **Blog Dark Mode**: Implemented a higher-contrast dark theme for the blog (list and detail) specifically optimized for Safari Mac, ensuring readability when system dark mode is active.
- 🐛 **Template Syntax**: Fixed a critical syntax error in `base.html` that was affecting CSS parsing.

#### Changed
- 📋 **Blog Section Limit**: Restricted the number of featured blog posts on the landing page to 3 for a cleaner, balanced 3-column layout.
- 🖼️ **Hero Optimization**: Set Intro background to `cover` and centered position for a better visual experience on mobile devices.

---

## [2.2.0] - 2026-01-23

### ✨ UI/UX Redesign & Layout Optimization

This release introduces a major aesthetic overhaul of key landing page sections and fixes several long-standing layout and template rendering issues.

#### Added
- 🎨 **New Education Design**: Premium dark-themed, card-based layout for "Educación y Certificaciones" with modern hover effects and radial gradients.
- 🖼️ **Enhanced Portfolio Cards**: Redesigned project cards with explicit "Ver Proyecto" buttons, high-contrast badges, and smooth image zoom transitions.
- 📐 **New Centering System**: Created `app/landing/static/landing/css/centering_fixes.css` to unify row widths and centering across all sections.

#### Changed
- 📏 **Blog List Optimization**: Increased content area width to 1300px (75% column) for better readability on large screens.
- 📨 **Contact Form Overhaul**: Standardized form width to 1200px, aligning perfectly with section headers.
- 📱 **Mobile Responsiveness**: Re-optimized card stacking and padding for small devices across redesigned sections.

#### Fixed
- 🐛 **Template Tag Brokenness**: Joined split Django template tags (`{{ ... }}`) in `resume.html`, `portfolio.html`, and `base.html` that were causing hardcoded-like text rendering in the UI.
- 📐 **Education Grid Alignment**: Fixed inconsistent card heights and widths in the formation section using flexbox.
- 🔲 **Layout Mismatches**: Resolved 100px width difference between section intros and their content blocks.

#### Technical
- 🏗️ Modernized `components.css` with cleaner, class-based styles instead of inline template styling.
- 🧹 Removed redundant and conflicting layout constraints.

---

## [2.1.0] - 2026-01-18

### 🎯 Project Cleanup & Code Quality

This release focuses on comprehensive code cleanup, removing unused templates, CSS classes, and improving overall codebase maintainability. No breaking changes. 100% backwards compatible.

#### Added
- ✨ Comprehensive documentation structure (`docs/changelog/`)
- 📊 Code audit reports and metrics
- 🔍 Automated cleanup analysis tools
- 📋 Checklist for future audits
- 🏗️ Professional documentation guidelines

#### Removed
- ❌ **HTML Templates** (2 files):
  - `app/gym/templates/product_table_htmx.html` - Unused HTMX template
  - `app/gym/templates/product_table_partial.html` - Unused partial template
  
- ❌ **CSS Classes** (105 unused selectors):
  - **Grid System Legacy** (23 classes): `.col-*`, `.mob-*`, `.tab-*` 
    - Replaced by Bootstrap 5 native grid system
  - **Typography** (26 classes): `.h01-.h06`, `.percent5-.percent100`
    - No references in current templates
  - **Components** (56 classes): `.folio-*`, `.services-*`, `.pagination-*`, etc.
    - Deprecated from previous template version

- 📝 **CSS Optimization**:
  - `app/landing/static/landing/css/base.css`: -23 lines (-2.6%)
  - `app/landing/static/landing/css/main.css`: -82 lines (-3.7%)
  - **Total CSS reduction: -105 lines (-3.2%)**

#### Changed
- 🔧 **Python Views**:
  - `app/landing/views.py`: `profile()` function now redirects to `private_area`
    - Was attempting to render non-existent `landing/profile.html`
    - Now uses proper redirect pattern

#### Fixed
- 🐛 Broken template reference in `landing/views.py:32`
- 🔗 Fixed orphaned template references
- ✅ Verified all Django URLs resolve correctly

#### Security
- ✅ No security regressions
- ✅ All imports validated
- ✅ No new vulnerabilities introduced

#### Performance
- ⚡ CSS file size reduced by 3.2% (~105 lines)
- ⚡ Reduced browser parsing overhead
- ⚡ Cleaner codebase = faster development

#### Testing
- ✅ `python manage.py check` - **PASS**
- ✅ All templates render correctly
- ✅ Admin interface fully functional
- ✅ No console errors in browser
- ✅ Responsive design verified
- ✅ All URLs working as expected
- ✅ Forms (contact, login) functional
- ✅ Static files serving correctly

#### Documentation
- 📖 [INDICE_LIMPIEZA.md](changelog/INDICE_LIMPIEZA.md) - Index of cleanup documentation
- 📖 [LIMPIEZA_HTML.md](changelog/LIMPIEZA_HTML.md) - HTML template cleanup details
- 📖 [LIMPIEZA_CSS_JS.md](changelog/LIMPIEZA_CSS_JS.md) - CSS classes analysis
- 📖 [LIMPIEZA_RESUMEN.txt](changelog/LIMPIEZA_RESUMEN.txt) - Executive summary
- 📖 [INFORME_TECNICO_LIMPIEZA.md](changelog/INFORME_TECNICO_LIMPIEZA.md) - Technical report
- 📖 [CHECKLIST_AUDITORIA.md](changelog/CHECKLIST_AUDITORIA.md) - Audit checklist

#### Migration Guide
No migration needed. This release is **100% backwards compatible**.

Simply pull the latest changes and verify locally:
```bash
git pull
python manage.py check
python manage.py runserver
```

#### Known Issues
- None identified

#### Notes
- Code cleanup focused on proven non-usage
- All removed code had zero references in codebase
- Conservative approach: high-confidence removals only
- Recommendation: Next review in 30 days

---

## [2.0.0] - 2026-01-18

### 🚀 Architectural Review & Code Improvements

Major architectural review implementing modern Django best practices.

#### Added
- ✨ Modularized Django settings (`settings/base.py`, `dev.py`, `prod.py`, `test.py`)
- 📝 Comprehensive logging configuration with rotating file handlers
- 🔍 Type hints across all views (Python 3.10+ compatible)
- ✅ Model validation with `clean()` methods
- 🎨 Enhanced Django admin interface with custom displays
- 🏷️ URL namespaces (gym, blog, prompts)
- 📊 Optimized context processors with caching
- 🔒 Security improvements (CSRF, HSTS, SSL redirect in production)

#### Fixed
- 🐛 Missing imports in `blog/models.py` (strip_tags, Truncator)
- 🐛 `__str__()` methods added to 8 models
- 🐛 Logging infrastructure (print → logger)
- 🐛 Database query optimization (prefetch_related, caching)
- 🐛 Form validation improvements

#### Performance
- ⚡ Context processors now cached (1-hour TTL)
- ⚡ Database queries optimized with prefetch_related
- ⚡ Better logging configuration for production

---

## [1.0.0] - 2025-12-21

### 🎉 Initial Release

Portfolio Django application with:
- Landing page with portfolio showcase
- Blog functionality with categories
- Gym/Products management
- Private user area with prompts
- Admin interface customization
- Bootstrap 5 responsive design

---

## Future Improvements (Roadmap)

### v2.2.0 (Planned)
- [ ] Migrate jQuery to vanilla JavaScript (remove jquery-2.1.3.min.js)
- [ ] Self-host fonts for better performance
- [ ] Minify CSS for production
- [ ] Implement critical CSS
- [ ] Add pytest test suite

### v2.3.0 (Planned)
- [ ] Migrate to Tailwind CSS (optional)
- [ ] Add dark mode support
- [ ] Implement service worker (PWA)
- [ ] Add Google Analytics integration

### v3.0.0 (Planned)
- [ ] Django upgrade to 7.0+
- [ ] Python 3.13+ support
- [ ] Full TypeScript migration (if frontend needed)
- [ ] API first architecture (DRF)

---

## How to Contribute

### Reporting Issues
1. Describe what went wrong
2. Describe what you expected
3. Include steps to reproduce
4. Check existing issues first

### Pull Requests
1. Create feature branch from `main`
2. Make your changes
3. Add/update documentation
4. Test locally: `python manage.py check`
5. Submit PR with clear description

### Code Quality Standards
- ✅ Type hints for all functions
- ✅ Docstrings for complex logic
- ✅ `python manage.py check` must pass
- ✅ No console errors
- ✅ Backwards compatible (or versioned)

---

## Release Notes

### Support
- **Python**: 3.12+
- **Django**: 6.0+
- **Database**: PostgreSQL (Supabase) / SQLite (dev)
- **Hosting**: Render.com

### Security
For security issues, email to: [contact info] instead of creating public issues.

---

## Maintenance Status

| Version | Status | Until |
|---------|--------|-------|
| 2.1.x | Active | 2026-06-18 |
| 2.0.x | Maintenance | 2026-04-18 |
| 1.0.x | Deprecated | 2026-02-18 |

---

## Archive

All historical releases and their documentation are available in `docs/changelog/`

', now(), 'import-script', 'Imported from CHANGELOG.md');
INSERT INTO documentum_document (title, slug, category_id, content_markdown, content_html, status, last_revision, stack_version, meta_description, meta_keywords, created_at, updated_at) VALUES ('📚 DOCUMENTACIÓN PROFESIONAL - ÍNDICE', 'documentacion-profesional-indice', (SELECT id FROM documentum_category WHERE slug='general'), '# 📚 DOCUMENTACIÓN PROFESIONAL - ÍNDICE

**Portfolio Django** - Documentación Completa y Profesional  
**Última actualización**: 30 de Enero de 2026  
**Versión del proyecto**: 2.2.5

---

## 🎯 EMPEZAR AQUÍ

### Para Diferentes Roles

#### 👨‍💼 **Project Manager / Stakeholder**
1. Leer: [CHANGELOG.md](CHANGELOG.md) (Sección v2.2.2)
2. Revisar: [docs/changelog/v2.1.0/LIMPIEZA_RESUMEN.txt](docs/changelog/v2.1.0/LIMPIEZA_RESUMEN.txt)
3. **Tiempo**: 10 minutos

---

#### 👨‍💻 **Frontend Developer**
1. Entender cambios: [CHANGELOG.md](CHANGELOG.md)
2. Leer análisis CSS: [docs/changelog/v2.1.0/LIMPIEZA_CSS_JS.md](docs/changelog/v2.1.0/LIMPIEZA_CSS_JS.md)
3. Revisar templates: [docs/changelog/v2.1.0/LIMPIEZA_HTML.md](docs/changelog/v2.1.0/LIMPIEZA_HTML.md)
4. **Tiempo**: 30 minutos

---

#### 🏗️ **Architect / Lead Developer**
1. Visión general: [CHANGELOG.md](CHANGELOG.md)
2. Análisis técnico: [docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md](docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md)
3. Auditoría: [docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md](docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md)
4. Futuro: [docs/FUTURAS_MEJORAS.md](docs/FUTURAS_MEJORAS.md)
5. **Tiempo**: 45 minutos

---

#### 🔍 **QA / Auditor**
1. Usar checklist: [docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md](docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md)
2. Referencia técnica: [docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md](docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md)
3. Ejecutar verificaciones (30 min)
4. **Tiempo**: 1 hora

---

#### 🚀 **DevOps / Deployment**
1. Release notes: [CHANGELOG.md](CHANGELOG.md) → v2.1.0
2. Deployment info: [docs/DEPLOYMENT.md](docs/DEPLOYMENT.md) (si existe)
3. Check: No migrations, no new dependencies
4. **Tiempo**: 15 minutos

---

## 📁 ESTRUCTURA DE DOCUMENTACIÓN

```
/
├── README.md                          ← Start here (project info)
├── CHANGELOG.md                       ← Version history (most important)
│
├── docs/                              ← Professional documentation
│   ├── README.md                      ← Documentation index (this folder)
│   ├── FUTURAS_MEJORAS.md            ← Roadmap & future improvements
│   ├── DEPLOYMENT.md                  ← (future)
│   ├── ARCHITECTURE.md                ← (future)
│   └── changelog/                     ← Versioned release notes
│       └── v2.1.0/                   ← Latest release
│           ├── INDICE_LIMPIEZA.md
│           ├── LIMPIEZA_HTML.md
│           ├── LIMPIEZA_CSS_JS.md
│           ├── LIMPIEZA_RESUMEN.txt
│           ├── INFORME_TECNICO_LIMPIEZA.md
│           └── CHECKLIST_AUDITORIA.md
│
├── app/                               ← Application code
│   ├── config/
│   ├── landing/
│   ├── blog/
│   ├── gym/
│   └── prompts/
│
└── [otros archivos del proyecto]
```

---

## 📖 GUÍA RÁPIDA DE DOCUMENTOS

### Top-Level Documents (Raíz del proyecto)

| Archivo | Propósito | Audiencia | Tiempo |
|---------|-----------|-----------|--------|
| **README.md** | Visión del proyecto | Todos | 5 min |
| **CHANGELOG.md** | Historial de cambios | Todos | 10 min |
| **requirements.txt** | Dependencias | Developers | 2 min |

---

### Documentation Folder

| Archivo | Propósito | Audiencia | Tiempo |
|---------|-----------|-----------|--------|
| **docs/README.md** | Índice de documentación | Todos | 10 min |
| **docs/FUTURAS_MEJORAS.md** | Roadmap & análisis | Architects | 15 min |
| **docs/DEPLOYMENT.md** | (Coming) | DevOps | — |
| **docs/ARCHITECTURE.md** | (Coming) | Architects | — |

---

### Changelog v2.1.0 (Cleanup Release)

| Archivo | Propósito | Tipo | Tamaño |
|---------|-----------|------|--------|
| INDICE_LIMPIEZA.md | Navigation | Index | 3.2 KB |
| LIMPIEZA_HTML.md | Template analysis | Technical | 6.5 KB |
| LIMPIEZA_CSS_JS.md | CSS analysis | Technical | 7.2 KB |
| LIMPIEZA_RESUMEN.txt | Executive summary | Summary | 1.5 KB |
| INFORME_TECNICO_LIMPIEZA.md | Complete report | Report | 9.8 KB |
| CHECKLIST_AUDITORIA.md | Verification | Checklist | 8.1 KB |

**Total**: 6 archivos, ~36 KB

---

## 🔍 BUSCAR POR TEMA

### "¿Qué cambió?"
- [CHANGELOG.md](CHANGELOG.md) - Overview
- [docs/changelog/v2.1.0/LIMPIEZA_RESUMEN.txt](docs/changelog/v2.1.0/LIMPIEZA_RESUMEN.txt) - Summary

### "¿Qué HTML se eliminó?"
- [docs/changelog/v2.1.0/LIMPIEZA_HTML.md](docs/changelog/v2.1.0/LIMPIEZA_HTML.md) - Details
- [docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md](docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md#-auditoría-html-templates) - Verification

### "¿Qué CSS se eliminó?"
- [docs/changelog/v2.1.0/LIMPIEZA_CSS_JS.md](docs/changelog/v2.1.0/LIMPIEZA_CSS_JS.md) - Full analysis
- [docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md](docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md#-impacto-total) - Metrics

### "¿Es seguro actualizar?"
- [docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md](docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md#-sign-off) - Sign-off
- [docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md](docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md#-análisis-de-riesgos) - Risk analysis

### "¿Qué hacer después?"
- [docs/FUTURAS_MEJORAS.md](docs/FUTURAS_MEJORAS.md) - Roadmap
- [CHANGELOG.md](CHANGELOG.md#future-improvements-roadmap) - v3.0 plans

---

## 📊 ESTADÍSTICAS DEL PROYECTO

### Última Limpieza (v2.1.0)
- **HTML Templates**: 28 → 26 (-2)
- **CSS Lines**: 3308 → 3203 (-105)
- **CSS Classes**: 152 → 47 (-105)
- **Breaking Changes**: 0 ✅
- **Tests Pass**: ✅ 100%

### Documentación Generada
- **Total Files**: 6
- **Total Size**: ~36 KB
- **Coverage**: 100% of changes
- **Quality**: Enterprise-grade

---

## 🚀 FLUJO DE TRABAJO RECOMENDADO

### Cuando haces un cambio en el código:

1. **Actualizar CHANGELOG.md**
   ```markdown
   ## [X.Y.Z] - YYYY-MM-DD
   ### Category
   - ✨ What changed
   ```

2. **Crear archivo de documentación** (si es cambio mayor)
   ```bash
   mkdir docs/changelog/vX.Y.Z/
   # Crear archivo de análisis
   ```

3. **Actualizar docs/README.md**
   - Añadir enlace a nuevo changelog
   - Actualizar tabla de versions

4. **Commit con mensaje claro**
   ```bash
   git commit -m "docs: add v2.1.0 cleanup documentation"
   ```

---

## ✅ CHECKLIST PARA CADA VERSIÓN

Antes de hacer release:

- [ ] CHANGELOG.md actualizado
- [ ] Documentación creada en `docs/changelog/vX.Y.Z/`
- [ ] `python manage.py check` pasa
- [ ] Tests ejecutados
- [ ] README.md actualizado (si necesario)
- [ ] docs/README.md con enlaces nuevos
- [ ] Git commits con mensajes claros

---

## 📞 CONTACTO Y PREGUNTAS

**¿No encuentras lo que buscas?**

1. Revisa [docs/README.md](docs/README.md)
2. Busca en CHANGELOG.md
3. Consulta [docs/changelog/v2.1.0/INDICE_LIMPIEZA.md](docs/changelog/v2.1.0/INDICE_LIMPIEZA.md)

**¿Tienes sugerencia de mejora?**
- Abre issue en repo (si applicable)
- Contacta al maintainer
- Sigue CONTRIBUTING.md (si existe)

---

## 📅 DOCUMENTO CONTROL

| Propiedad | Valor |
|-----------|-------|
| **Última Actualización** | 23 de Enero de 2026 |
| **Versión del Proyecto** | 2.2.3 |
| **Versión de este Documento** | 1.0 |
| **Estado** | ✅ Activo |
| **Próxima Revisión** | 2026-02-18 |

---

## 📋 RELACIONADOS

- [CHANGELOG.md](CHANGELOG.md) - Version history
- [README.md](README.md) - Project overview
- [docs/README.md](docs/README.md) - Documentation index
- [docs/FUTURAS_MEJORAS.md](docs/FUTURAS_MEJORAS.md) - Future roadmap

---

**Documentación profesional desarrollada automáticamente**  
*Proyecto: Portfolio Django - Javier Hernández Martin*  
*Siguiendo estándares internacionales de documentación*
', '', 'published', now(), '', '# 📚 DOCUMENTACIÓN PROFESIONAL - ÍNDICE', '', now(), now()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO documentum_documentversion (document_id, content_markdown, created_at, changed_by, change_summary) VALUES ((SELECT id FROM documentum_document WHERE slug='documentacion-profesional-indice'), '# 📚 DOCUMENTACIÓN PROFESIONAL - ÍNDICE

**Portfolio Django** - Documentación Completa y Profesional  
**Última actualización**: 30 de Enero de 2026  
**Versión del proyecto**: 2.2.5

---

## 🎯 EMPEZAR AQUÍ

### Para Diferentes Roles

#### 👨‍💼 **Project Manager / Stakeholder**
1. Leer: [CHANGELOG.md](CHANGELOG.md) (Sección v2.2.2)
2. Revisar: [docs/changelog/v2.1.0/LIMPIEZA_RESUMEN.txt](docs/changelog/v2.1.0/LIMPIEZA_RESUMEN.txt)
3. **Tiempo**: 10 minutos

---

#### 👨‍💻 **Frontend Developer**
1. Entender cambios: [CHANGELOG.md](CHANGELOG.md)
2. Leer análisis CSS: [docs/changelog/v2.1.0/LIMPIEZA_CSS_JS.md](docs/changelog/v2.1.0/LIMPIEZA_CSS_JS.md)
3. Revisar templates: [docs/changelog/v2.1.0/LIMPIEZA_HTML.md](docs/changelog/v2.1.0/LIMPIEZA_HTML.md)
4. **Tiempo**: 30 minutos

---

#### 🏗️ **Architect / Lead Developer**
1. Visión general: [CHANGELOG.md](CHANGELOG.md)
2. Análisis técnico: [docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md](docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md)
3. Auditoría: [docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md](docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md)
4. Futuro: [docs/FUTURAS_MEJORAS.md](docs/FUTURAS_MEJORAS.md)
5. **Tiempo**: 45 minutos

---

#### 🔍 **QA / Auditor**
1. Usar checklist: [docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md](docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md)
2. Referencia técnica: [docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md](docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md)
3. Ejecutar verificaciones (30 min)
4. **Tiempo**: 1 hora

---

#### 🚀 **DevOps / Deployment**
1. Release notes: [CHANGELOG.md](CHANGELOG.md) → v2.1.0
2. Deployment info: [docs/DEPLOYMENT.md](docs/DEPLOYMENT.md) (si existe)
3. Check: No migrations, no new dependencies
4. **Tiempo**: 15 minutos

---

## 📁 ESTRUCTURA DE DOCUMENTACIÓN

```
/
├── README.md                          ← Start here (project info)
├── CHANGELOG.md                       ← Version history (most important)
│
├── docs/                              ← Professional documentation
│   ├── README.md                      ← Documentation index (this folder)
│   ├── FUTURAS_MEJORAS.md            ← Roadmap & future improvements
│   ├── DEPLOYMENT.md                  ← (future)
│   ├── ARCHITECTURE.md                ← (future)
│   └── changelog/                     ← Versioned release notes
│       └── v2.1.0/                   ← Latest release
│           ├── INDICE_LIMPIEZA.md
│           ├── LIMPIEZA_HTML.md
│           ├── LIMPIEZA_CSS_JS.md
│           ├── LIMPIEZA_RESUMEN.txt
│           ├── INFORME_TECNICO_LIMPIEZA.md
│           └── CHECKLIST_AUDITORIA.md
│
├── app/                               ← Application code
│   ├── config/
│   ├── landing/
│   ├── blog/
│   ├── gym/
│   └── prompts/
│
└── [otros archivos del proyecto]
```

---

## 📖 GUÍA RÁPIDA DE DOCUMENTOS

### Top-Level Documents (Raíz del proyecto)

| Archivo | Propósito | Audiencia | Tiempo |
|---------|-----------|-----------|--------|
| **README.md** | Visión del proyecto | Todos | 5 min |
| **CHANGELOG.md** | Historial de cambios | Todos | 10 min |
| **requirements.txt** | Dependencias | Developers | 2 min |

---

### Documentation Folder

| Archivo | Propósito | Audiencia | Tiempo |
|---------|-----------|-----------|--------|
| **docs/README.md** | Índice de documentación | Todos | 10 min |
| **docs/FUTURAS_MEJORAS.md** | Roadmap & análisis | Architects | 15 min |
| **docs/DEPLOYMENT.md** | (Coming) | DevOps | — |
| **docs/ARCHITECTURE.md** | (Coming) | Architects | — |

---

### Changelog v2.1.0 (Cleanup Release)

| Archivo | Propósito | Tipo | Tamaño |
|---------|-----------|------|--------|
| INDICE_LIMPIEZA.md | Navigation | Index | 3.2 KB |
| LIMPIEZA_HTML.md | Template analysis | Technical | 6.5 KB |
| LIMPIEZA_CSS_JS.md | CSS analysis | Technical | 7.2 KB |
| LIMPIEZA_RESUMEN.txt | Executive summary | Summary | 1.5 KB |
| INFORME_TECNICO_LIMPIEZA.md | Complete report | Report | 9.8 KB |
| CHECKLIST_AUDITORIA.md | Verification | Checklist | 8.1 KB |

**Total**: 6 archivos, ~36 KB

---

## 🔍 BUSCAR POR TEMA

### "¿Qué cambió?"
- [CHANGELOG.md](CHANGELOG.md) - Overview
- [docs/changelog/v2.1.0/LIMPIEZA_RESUMEN.txt](docs/changelog/v2.1.0/LIMPIEZA_RESUMEN.txt) - Summary

### "¿Qué HTML se eliminó?"
- [docs/changelog/v2.1.0/LIMPIEZA_HTML.md](docs/changelog/v2.1.0/LIMPIEZA_HTML.md) - Details
- [docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md](docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md#-auditoría-html-templates) - Verification

### "¿Qué CSS se eliminó?"
- [docs/changelog/v2.1.0/LIMPIEZA_CSS_JS.md](docs/changelog/v2.1.0/LIMPIEZA_CSS_JS.md) - Full analysis
- [docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md](docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md#-impacto-total) - Metrics

### "¿Es seguro actualizar?"
- [docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md](docs/changelog/v2.1.0/CHECKLIST_AUDITORIA.md#-sign-off) - Sign-off
- [docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md](docs/changelog/v2.1.0/INFORME_TECNICO_LIMPIEZA.md#-análisis-de-riesgos) - Risk analysis

### "¿Qué hacer después?"
- [docs/FUTURAS_MEJORAS.md](docs/FUTURAS_MEJORAS.md) - Roadmap
- [CHANGELOG.md](CHANGELOG.md#future-improvements-roadmap) - v3.0 plans

---

## 📊 ESTADÍSTICAS DEL PROYECTO

### Última Limpieza (v2.1.0)
- **HTML Templates**: 28 → 26 (-2)
- **CSS Lines**: 3308 → 3203 (-105)
- **CSS Classes**: 152 → 47 (-105)
- **Breaking Changes**: 0 ✅
- **Tests Pass**: ✅ 100%

### Documentación Generada
- **Total Files**: 6
- **Total Size**: ~36 KB
- **Coverage**: 100% of changes
- **Quality**: Enterprise-grade

---

## 🚀 FLUJO DE TRABAJO RECOMENDADO

### Cuando haces un cambio en el código:

1. **Actualizar CHANGELOG.md**
   ```markdown
   ## [X.Y.Z] - YYYY-MM-DD
   ### Category
   - ✨ What changed
   ```

2. **Crear archivo de documentación** (si es cambio mayor)
   ```bash
   mkdir docs/changelog/vX.Y.Z/
   # Crear archivo de análisis
   ```

3. **Actualizar docs/README.md**
   - Añadir enlace a nuevo changelog
   - Actualizar tabla de versions

4. **Commit con mensaje claro**
   ```bash
   git commit -m "docs: add v2.1.0 cleanup documentation"
   ```

---

## ✅ CHECKLIST PARA CADA VERSIÓN

Antes de hacer release:

- [ ] CHANGELOG.md actualizado
- [ ] Documentación creada en `docs/changelog/vX.Y.Z/`
- [ ] `python manage.py check` pasa
- [ ] Tests ejecutados
- [ ] README.md actualizado (si necesario)
- [ ] docs/README.md con enlaces nuevos
- [ ] Git commits con mensajes claros

---

## 📞 CONTACTO Y PREGUNTAS

**¿No encuentras lo que buscas?**

1. Revisa [docs/README.md](docs/README.md)
2. Busca en CHANGELOG.md
3. Consulta [docs/changelog/v2.1.0/INDICE_LIMPIEZA.md](docs/changelog/v2.1.0/INDICE_LIMPIEZA.md)

**¿Tienes sugerencia de mejora?**
- Abre issue en repo (si applicable)
- Contacta al maintainer
- Sigue CONTRIBUTING.md (si existe)

---

## 📅 DOCUMENTO CONTROL

| Propiedad | Valor |
|-----------|-------|
| **Última Actualización** | 23 de Enero de 2026 |
| **Versión del Proyecto** | 2.2.3 |
| **Versión de este Documento** | 1.0 |
| **Estado** | ✅ Activo |
| **Próxima Revisión** | 2026-02-18 |

---

## 📋 RELACIONADOS

- [CHANGELOG.md](CHANGELOG.md) - Version history
- [README.md](README.md) - Project overview
- [docs/README.md](docs/README.md) - Documentation index
- [docs/FUTURAS_MEJORAS.md](docs/FUTURAS_MEJORAS.md) - Future roadmap

---

**Documentación profesional desarrollada automáticamente**  
*Proyecto: Portfolio Django - Javier Hernández Martin*  
*Siguiendo estándares internacionales de documentación*
', now(), 'import-script', 'Imported from DOCUMENTACION.md');
INSERT INTO documentum_document (title, slug, category_id, content_markdown, content_html, status, last_revision, stack_version, meta_description, meta_keywords, created_at, updated_at) VALUES ('PRODUCT.md', 'productmd', (SELECT id FROM documentum_category WHERE slug='general'), '# PRODUCT.md

## Visión del Producto

Este portfolio profesional se concibe como un **CMS técnico escalable**, diseñado no solo para mostrar proyectos, sino para evidenciar la **capacidad de gestionar el ciclo de vida completo de un producto técnico**.  
El enfoque estratégico incluye **resiliencia**, **automatización de procesos críticos** y una **experiencia de usuario (UX) optimizada**, asegurando que la plataforma sea **robusta, mantenible y preparada para el crecimiento futuro**.  
Se prioriza un **MVP funcional** inicialmente, con capacidad de **extender funcionalidades** sin comprometer estabilidad ni desempeño.

---

## User Personas

1. **Technical Recruiter**  
   - Busca evaluar rápidamente competencias técnicas, experiencia práctica y conocimiento de frameworks modernos (Django, PostgreSQL).  
   - Necesita un acceso ágil a ejemplos de proyectos y métricas de impacto.

2. **Hiring Manager**  
   - Evalúa la **visión estratégica** y habilidades de gestión de producto.  
   - Interesado en cómo los desafíos técnicos se abordan con soluciones resilientes y medibles.  
   - Valora la presentación clara de roadmap, KPIs y resultados alcanzados.

3. **Administrador del Sistema / CTO**  
   - Se enfoca en la **arquitectura, escalabilidad y disponibilidad** de la plataforma.  
   - Necesita comprender la implementación técnica, backups automáticos y estrategias de disaster recovery.  

---

## Desafíos Técnicos y Soluciones de Producto

### Desafío: Limitación de 90 días en Render (Base de Datos)

Render Free proporciona PostgreSQL con **persistencia limitada a 90 días**, lo que representa un riesgo significativo de pérdida de datos para un portfolio profesional.

### Solución Implementada

- Desarrollo de un **sistema automatizado de backup y restauración** usando `db_backup.json`.  
- Integración de comandos de gestión personalizados (`setup_db`) para:
  - Detectar base de datos vacía.
  - Restaurar automáticamente desde JSON.
  - Exportar datos actualizados en cualquier momento.  
- Esta solución garantiza **resiliencia y disaster recovery**, demostrando competencias de **gestión de producto técnico**, control de riesgos y **visión estratégica de continuidad**.

---

## Roadmap Estratégico

- [x] **Fase 1: Cimentación (Completada)**  
  - Implementación de la estructura base del CMS en Django 5.1 y PostgreSQL.  
  - Definición de modelos, autenticación y despliegue inicial en Render.  
  - Primer MVP funcional con navegación básica y presentación de proyectos.

- [x] **Fase 2: Optimización (Completada v2.2.4)**  
  - Integración de **automatización de backups y restauración**.  
  - Mejora de **UX/UI** y experiencia de navegación.  
  - **Performance Extrema**: Eliminación de jQuery, Minificación HTML y Vanilla JS.  
  - Optimización de **SEO y Core Web Vitals**.  
  - Implementación de métricas de disponibilidad y logging.

- [ ] **Fase 3: Escalabilidad (Futuro)**  
  - Migración a infraestructuras con mayor persistencia (Supabase Pooler u otros).  
  - Introducción de nuevas secciones y funcionalidades dinámicas.  
  - Integración de dashboards de métricas avanzadas y análisis estratégico.

---

## KPIs y Métricas

1. **Performance**  
   - Tiempo de carga de página (<2s).  
   - Número de queries optimizadas por proyecto.

2. **SEO**  
   - Visibilidad en motores de búsqueda.  
   - Indexación de proyectos y descripciones técnicas.

3. **Disponibilidad y Resiliencia**  
   - % de uptime de la plataforma.  
   - Ejecución exitosa de backups automáticos y restauraciones.  
   - Tiempo de recuperación ante fallos (RTO) y pérdida de datos mínima.

---

## Nota Final

Este documento refleja la **visión estratégica y capacidades técnicas** de gestión de producto, mostrando cómo se abordan desafíos de arquitectura, resiliencia y escalabilidad en un entorno profesional.  
Está alineado con mi **perfil de Technical Product Manager**, demostrando dominio en **MVP, UX, SEO, KPIs y gestión de riesgo técnico**.
', '', 'published', now(), '', '# PRODUCT.md', '', now(), now()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO documentum_documentversion (document_id, content_markdown, created_at, changed_by, change_summary) VALUES ((SELECT id FROM documentum_document WHERE slug='productmd'), '# PRODUCT.md

## Visión del Producto

Este portfolio profesional se concibe como un **CMS técnico escalable**, diseñado no solo para mostrar proyectos, sino para evidenciar la **capacidad de gestionar el ciclo de vida completo de un producto técnico**.  
El enfoque estratégico incluye **resiliencia**, **automatización de procesos críticos** y una **experiencia de usuario (UX) optimizada**, asegurando que la plataforma sea **robusta, mantenible y preparada para el crecimiento futuro**.  
Se prioriza un **MVP funcional** inicialmente, con capacidad de **extender funcionalidades** sin comprometer estabilidad ni desempeño.

---

## User Personas

1. **Technical Recruiter**  
   - Busca evaluar rápidamente competencias técnicas, experiencia práctica y conocimiento de frameworks modernos (Django, PostgreSQL).  
   - Necesita un acceso ágil a ejemplos de proyectos y métricas de impacto.

2. **Hiring Manager**  
   - Evalúa la **visión estratégica** y habilidades de gestión de producto.  
   - Interesado en cómo los desafíos técnicos se abordan con soluciones resilientes y medibles.  
   - Valora la presentación clara de roadmap, KPIs y resultados alcanzados.

3. **Administrador del Sistema / CTO**  
   - Se enfoca en la **arquitectura, escalabilidad y disponibilidad** de la plataforma.  
   - Necesita comprender la implementación técnica, backups automáticos y estrategias de disaster recovery.  

---

## Desafíos Técnicos y Soluciones de Producto

### Desafío: Limitación de 90 días en Render (Base de Datos)

Render Free proporciona PostgreSQL con **persistencia limitada a 90 días**, lo que representa un riesgo significativo de pérdida de datos para un portfolio profesional.

### Solución Implementada

- Desarrollo de un **sistema automatizado de backup y restauración** usando `db_backup.json`.  
- Integración de comandos de gestión personalizados (`setup_db`) para:
  - Detectar base de datos vacía.
  - Restaurar automáticamente desde JSON.
  - Exportar datos actualizados en cualquier momento.  
- Esta solución garantiza **resiliencia y disaster recovery**, demostrando competencias de **gestión de producto técnico**, control de riesgos y **visión estratégica de continuidad**.

---

## Roadmap Estratégico

- [x] **Fase 1: Cimentación (Completada)**  
  - Implementación de la estructura base del CMS en Django 5.1 y PostgreSQL.  
  - Definición de modelos, autenticación y despliegue inicial en Render.  
  - Primer MVP funcional con navegación básica y presentación de proyectos.

- [x] **Fase 2: Optimización (Completada v2.2.4)**  
  - Integración de **automatización de backups y restauración**.  
  - Mejora de **UX/UI** y experiencia de navegación.  
  - **Performance Extrema**: Eliminación de jQuery, Minificación HTML y Vanilla JS.  
  - Optimización de **SEO y Core Web Vitals**.  
  - Implementación de métricas de disponibilidad y logging.

- [ ] **Fase 3: Escalabilidad (Futuro)**  
  - Migración a infraestructuras con mayor persistencia (Supabase Pooler u otros).  
  - Introducción de nuevas secciones y funcionalidades dinámicas.  
  - Integración de dashboards de métricas avanzadas y análisis estratégico.

---

## KPIs y Métricas

1. **Performance**  
   - Tiempo de carga de página (<2s).  
   - Número de queries optimizadas por proyecto.

2. **SEO**  
   - Visibilidad en motores de búsqueda.  
   - Indexación de proyectos y descripciones técnicas.

3. **Disponibilidad y Resiliencia**  
   - % de uptime de la plataforma.  
   - Ejecución exitosa de backups automáticos y restauraciones.  
   - Tiempo de recuperación ante fallos (RTO) y pérdida de datos mínima.

---

## Nota Final

Este documento refleja la **visión estratégica y capacidades técnicas** de gestión de producto, mostrando cómo se abordan desafíos de arquitectura, resiliencia y escalabilidad en un entorno profesional.  
Está alineado con mi **perfil de Technical Product Manager**, demostrando dominio en **MVP, UX, SEO, KPIs y gestión de riesgo técnico**.
', now(), 'import-script', 'Imported from PRODUCT.md');
INSERT INTO documentum_document (title, slug, category_id, content_markdown, content_html, status, last_revision, stack_version, meta_description, meta_keywords, created_at, updated_at) VALUES ('🚀 Portfolio Profesional - Javier Hernández Martin', 'portfolio-profesional-javier-hernandez-martin', (SELECT id FROM documentum_category WHERE slug='general'), '# 🚀 Portfolio Profesional - Javier Hernández Martin

Este proyecto es mi **portfolio profesional y plataforma técnica**, diseñado para centralizar mi experiencia, proyectos de desarrollo y una **biblioteca especializada de prompts** para Product Managers.  
Construido con **Django 5.1** y PostgreSQL (ahora gestionada en **Supabase**), desplegado de forma automatizada en **Render**.

🌐 **Sitio en vivo:**  
Hernandezpalo.es

---

## 🛠️ Tecnologías Aplicadas

### **Backend & Lógica**
- **Python 3.11+**: Lenguaje principal para lógica de negocio y scripts de administración.
- **Django 5.1**: Framework robusto para gestión de datos, seguridad y routing.
- **Django Sites & Sitemaps**: SEO dinámico y gestión avanzada de URLs.
- **PostgreSQL (Supabase)**: Base de datos relacional, ahora con persistencia segura y pooler de sesión.

### **Frontend (Hybrid Architecture)**
- **Public Area (Landing/Blog)**: 
  - **Vanilla JS (ES6+)**: Cero dependencias (No jQuery) para máxima velocidad.
  - **Custom CSS (Kards)**: Diseño ligero con CSS moderno (`clamp`, `flexbox`).
  - **HTML Minification**: Compresión automática en producción.
- **Private Area (Portal)**: 
  - **Bootstrap 5**: Gestión eficiente de dashboards y formularios.
  - **Bootstrap Icons**: Librería de iconos vectoriales.

---

## 📁 Estructura del Proyecto (Django Apps)

- **app.landing**: Página principal, SEO, Open Graph y lógica del portafolio.  
- **app.prompts**: Biblioteca privada de prompts con autenticación para herramientas de IA.  
- **app.gym**: Módulo dedicado a seguimiento y lógica específica (en desarrollo).  
- **app.config**: Configuración central de Django (`settings.py`, `urls.py`, `wsgi.py`).

---

## 🚀 Despliegue en Render

El sitio sigue una **arquitectura CI/CD**:

- **Web Service**: Despliegue automático desde la rama `main`.  
- **Database**: PostgreSQL en **Supabase**, con session pooler y SSL obligatorio.  
- **Environment Variables**: Seguridad y parametrización mediante `.env`. Variables principales:
  - `DEBUG` = False en producción.
  - `SECRET_KEY` = gestionada de forma privada.
  - `DATABASE_URL` = conexión mediante `dj-database-url` con Supabase Pooler.
- **Archivos Estáticos**: Gestionados con WhiteNoise, optimizando CSS/JS.

---

## 📦 Gestión de Datos y Resiliencia

Se ha implementado un **sistema de backup y restauración JSON** para proteger la integridad del portfolio:

- **Generar copia**: Exporta todos los datos de `landing` y `gym` a `db_backup.json`.
- **Ver JSON**: Permite inspeccionar el contenido del backup desde la interfaz web.
- **Descargar**: Descarga la copia localmente para almacenamiento externo.
- **Restaurar datos**: Valida y carga automáticamente el JSON, garantizando resiliencia y continuidad.  

Esta funcionalidad asegura **Disaster Recovery** y demuestra experiencia en **gestión de productos técnicos** y **automatización de procesos críticos**.

---

## 📊 SEO y Datos del Portfolio

- **Sitemap XML**: `/sitemap.xml` generado dinámicamente para indexación.
- **Open Graph**: Mejora la presentación en LinkedIn y redes sociales.  
- **Datos Estructurados (JSON-LD)**: `@type: Person` para que motores de búsqueda identifiquen mi perfil profesional.

---

## 🛠️ Instalación Local

1. **Clonar repositorio**:
   ```bash
   git clone [url-del-repositorio]
   cd porfolio

Crear entorno virtual e instalar dependencias:

python -m venv venv

source venv/bin/activate  # En Windows: venv\Scripts\activate

pip install -r requirements.txt

Configurar variables de entorno: Crea un archivo .env en la raíz con tus credenciales locales.

Migraciones y ejecución:

python manage.py migrate

python manage.py runserver

Web:Hernandezpalo.es

Desarrollado con ❤️ por Javier Hernández Martin.


', '', 'published', now(), '', '# 🚀 Portfolio Profesional - Javier Hernández Martin', '', now(), now()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO documentum_documentversion (document_id, content_markdown, created_at, changed_by, change_summary) VALUES ((SELECT id FROM documentum_document WHERE slug='portfolio-profesional-javier-hernandez-martin'), '# 🚀 Portfolio Profesional - Javier Hernández Martin

Este proyecto es mi **portfolio profesional y plataforma técnica**, diseñado para centralizar mi experiencia, proyectos de desarrollo y una **biblioteca especializada de prompts** para Product Managers.  
Construido con **Django 5.1** y PostgreSQL (ahora gestionada en **Supabase**), desplegado de forma automatizada en **Render**.

🌐 **Sitio en vivo:**  
Hernandezpalo.es

---

## 🛠️ Tecnologías Aplicadas

### **Backend & Lógica**
- **Python 3.11+**: Lenguaje principal para lógica de negocio y scripts de administración.
- **Django 5.1**: Framework robusto para gestión de datos, seguridad y routing.
- **Django Sites & Sitemaps**: SEO dinámico y gestión avanzada de URLs.
- **PostgreSQL (Supabase)**: Base de datos relacional, ahora con persistencia segura y pooler de sesión.

### **Frontend (Hybrid Architecture)**
- **Public Area (Landing/Blog)**: 
  - **Vanilla JS (ES6+)**: Cero dependencias (No jQuery) para máxima velocidad.
  - **Custom CSS (Kards)**: Diseño ligero con CSS moderno (`clamp`, `flexbox`).
  - **HTML Minification**: Compresión automática en producción.
- **Private Area (Portal)**: 
  - **Bootstrap 5**: Gestión eficiente de dashboards y formularios.
  - **Bootstrap Icons**: Librería de iconos vectoriales.

---

## 📁 Estructura del Proyecto (Django Apps)

- **app.landing**: Página principal, SEO, Open Graph y lógica del portafolio.  
- **app.prompts**: Biblioteca privada de prompts con autenticación para herramientas de IA.  
- **app.gym**: Módulo dedicado a seguimiento y lógica específica (en desarrollo).  
- **app.config**: Configuración central de Django (`settings.py`, `urls.py`, `wsgi.py`).

---

## 🚀 Despliegue en Render

El sitio sigue una **arquitectura CI/CD**:

- **Web Service**: Despliegue automático desde la rama `main`.  
- **Database**: PostgreSQL en **Supabase**, con session pooler y SSL obligatorio.  
- **Environment Variables**: Seguridad y parametrización mediante `.env`. Variables principales:
  - `DEBUG` = False en producción.
  - `SECRET_KEY` = gestionada de forma privada.
  - `DATABASE_URL` = conexión mediante `dj-database-url` con Supabase Pooler.
- **Archivos Estáticos**: Gestionados con WhiteNoise, optimizando CSS/JS.

---

## 📦 Gestión de Datos y Resiliencia

Se ha implementado un **sistema de backup y restauración JSON** para proteger la integridad del portfolio:

- **Generar copia**: Exporta todos los datos de `landing` y `gym` a `db_backup.json`.
- **Ver JSON**: Permite inspeccionar el contenido del backup desde la interfaz web.
- **Descargar**: Descarga la copia localmente para almacenamiento externo.
- **Restaurar datos**: Valida y carga automáticamente el JSON, garantizando resiliencia y continuidad.  

Esta funcionalidad asegura **Disaster Recovery** y demuestra experiencia en **gestión de productos técnicos** y **automatización de procesos críticos**.

---

## 📊 SEO y Datos del Portfolio

- **Sitemap XML**: `/sitemap.xml` generado dinámicamente para indexación.
- **Open Graph**: Mejora la presentación en LinkedIn y redes sociales.  
- **Datos Estructurados (JSON-LD)**: `@type: Person` para que motores de búsqueda identifiquen mi perfil profesional.

---

## 🛠️ Instalación Local

1. **Clonar repositorio**:
   ```bash
   git clone [url-del-repositorio]
   cd porfolio

Crear entorno virtual e instalar dependencias:

python -m venv venv

source venv/bin/activate  # En Windows: venv\Scripts\activate

pip install -r requirements.txt

Configurar variables de entorno: Crea un archivo .env en la raíz con tus credenciales locales.

Migraciones y ejecución:

python manage.py migrate

python manage.py runserver

Web:Hernandezpalo.es

Desarrollado con ❤️ por Javier Hernández Martin.


', now(), 'import-script', 'Imported from README.md');
INSERT INTO documentum_document (title, slug, category_id, content_markdown, content_html, status, last_revision, stack_version, meta_description, meta_keywords, created_at, updated_at) VALUES ('License Select2.F94142512C91', 'license-select2f94142512c91', (SELECT id FROM documentum_category WHERE slug='app'), 'The MIT License (MIT)

Copyright (c) 2012-2017 Kevin Brown, Igor Vaynberg, and Select2 contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
', '', 'published', now(), '', 'The MIT License (MIT)', '', now(), now()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO documentum_documentversion (document_id, content_markdown, created_at, changed_by, change_summary) VALUES ((SELECT id FROM documentum_document WHERE slug='license-select2f94142512c91'), 'The MIT License (MIT)

Copyright (c) 2012-2017 Kevin Brown, Igor Vaynberg, and Select2 contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
', now(), 'import-script', 'Imported from app/staticfiles/admin/css/vendor/select2/LICENSE-SELECT2.f94142512c91.md');
INSERT INTO documentum_document (title, slug, category_id, content_markdown, content_html, status, last_revision, stack_version, meta_description, meta_keywords, created_at, updated_at) VALUES ('Information about icons in this directory', 'information-about-icons-in-this-directory', (SELECT id FROM documentum_category WHERE slug='app'), '# Information about icons in this directory

## License

All icons in this directory are provided by
[Font Awesome Free](https://fontawesome.com), version 6.7.2.

- The icons are licensed under the [Creative Commons Attribution 4.0
  International (CC-BY-4.0)](https://creativecommons.org/licenses/by/4.0/)
  license.
- This license allows you to use, modify, and distribute the icons, provided
  proper attribution is given.

## Usage

- You may use, modify, and distribute the icons in this repository in
  compliance with the [Creative Commons Attribution 4.0 International
  (CC-BY-4.0)](https://creativecommons.org/licenses/by/4.0/) license.

## Modifications

- These icons have been resized, recolored, or otherwise modified to fit the
  requirements of this project.

- These modifications alter the appearance of the original icons but remain
  covered under the terms of the
  [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/) license.

## Contributing SVG Icons

To ensure visual consistency, traceability, and proper license attribution,
follow these guidelines. This applies when adding or modifying icons.

## ⚠️ Important: Changing Font Awesome Version

If you update to a different Font Awesome version, you must **update all SVG
files** and **comments inside the files** to reflect the new version number and
licensing URL accordingly. For example:

* Original:
```xml
<!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.-->
```
* Updated:
```xml
<!--!Font Awesome Free X.Y.Z by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright YYYY Fonticons, Inc.-->
```

## Adding a new icon

1. Use only [Font Awesome Free Icons](https://fontawesome.com/icons).
2. Save the icon as an .svg file in this directory.
3. Include the following attribution comment at the top of the file (do not
   change it):
```xml
<!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.-->
```
4. Right before the `<path>` element, add the following metadata comment with
   the appropriate values:
```xml
<!--
  Icon Name: [icon-name]
  Icon Family: [classic | sharp | brands | etc.]
  Icon Style: [solid | regular | light | thin | duotone | etc.]
-->
```

### Example SVG Structure

```xml
<svg width="13" height="13" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
  <!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.-->
  <!--
    Icon Name: plus
    Icon Family: classic
    Icon Style: solid
  -->
  <path fill="#5fa225" stroke="#5fa225" stroke-width="30" d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 144L48 224c-17.7 0-32 14.3-32 32s14.3 32 32 32l144 0 0 144c0 17.7 14.3 32 32 32s32-14.3 32-32l0-144 144 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-144 0 0-144z"/>
</svg>
```
', '', 'published', now(), '', '# Information about icons in this directory', '', now(), now()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO documentum_documentversion (document_id, content_markdown, created_at, changed_by, change_summary) VALUES ((SELECT id FROM documentum_document WHERE slug='information-about-icons-in-this-directory'), '# Information about icons in this directory

## License

All icons in this directory are provided by
[Font Awesome Free](https://fontawesome.com), version 6.7.2.

- The icons are licensed under the [Creative Commons Attribution 4.0
  International (CC-BY-4.0)](https://creativecommons.org/licenses/by/4.0/)
  license.
- This license allows you to use, modify, and distribute the icons, provided
  proper attribution is given.

## Usage

- You may use, modify, and distribute the icons in this repository in
  compliance with the [Creative Commons Attribution 4.0 International
  (CC-BY-4.0)](https://creativecommons.org/licenses/by/4.0/) license.

## Modifications

- These icons have been resized, recolored, or otherwise modified to fit the
  requirements of this project.

- These modifications alter the appearance of the original icons but remain
  covered under the terms of the
  [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/) license.

## Contributing SVG Icons

To ensure visual consistency, traceability, and proper license attribution,
follow these guidelines. This applies when adding or modifying icons.

## ⚠️ Important: Changing Font Awesome Version

If you update to a different Font Awesome version, you must **update all SVG
files** and **comments inside the files** to reflect the new version number and
licensing URL accordingly. For example:

* Original:
```xml
<!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.-->
```
* Updated:
```xml
<!--!Font Awesome Free X.Y.Z by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright YYYY Fonticons, Inc.-->
```

## Adding a new icon

1. Use only [Font Awesome Free Icons](https://fontawesome.com/icons).
2. Save the icon as an .svg file in this directory.
3. Include the following attribution comment at the top of the file (do not
   change it):
```xml
<!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.-->
```
4. Right before the `<path>` element, add the following metadata comment with
   the appropriate values:
```xml
<!--
  Icon Name: [icon-name]
  Icon Family: [classic | sharp | brands | etc.]
  Icon Style: [solid | regular | light | thin | duotone | etc.]
-->
```

### Example SVG Structure

```xml
<svg width="13" height="13" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
  <!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.-->
  <!--
    Icon Name: plus
    Icon Family: classic
    Icon Style: solid
  -->
  <path fill="#5fa225" stroke="#5fa225" stroke-width="30" d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 144L48 224c-17.7 0-32 14.3-32 32s14.3 32 32 32l144 0 0 144c0 17.7 14.3 32 32 32s32-14.3 32-32l0-144 144 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-144 0 0-144z"/>
</svg>
```
', now(), 'import-script', 'Imported from app/staticfiles/admin/img/README.2e7bc30d034a.md');
INSERT INTO documentum_document (title, slug, category_id, content_markdown, content_html, status, last_revision, stack_version, meta_description, meta_keywords, created_at, updated_at) VALUES ('License.F94142512C91', 'licensef94142512c91', (SELECT id FROM documentum_category WHERE slug='app'), 'The MIT License (MIT)

Copyright (c) 2012-2017 Kevin Brown, Igor Vaynberg, and Select2 contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
', '', 'published', now(), '', 'The MIT License (MIT)', '', now(), now()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO documentum_documentversion (document_id, content_markdown, created_at, changed_by, change_summary) VALUES ((SELECT id FROM documentum_document WHERE slug='licensef94142512c91'), 'The MIT License (MIT)

Copyright (c) 2012-2017 Kevin Brown, Igor Vaynberg, and Select2 contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
', now(), 'import-script', 'Imported from app/staticfiles/admin/js/vendor/select2/LICENSE.f94142512c91.md');
COMMIT;
