#!/usr/bin/env python3
"""Genera un SQL con INSERTs para poblar la app `documentum` a partir de archivos Markdown del repo.
Salida: documentum_seed.sql en la raíz del repositorio.

Uso:
    python app/documentum/scripts/generate_documentum_sql.py [--root PATH] [--out FILE]

Diseñado para SQLite (usa CURRENT_TIMESTAMP para timestamps).
"""

import argparse
from pathlib import Path
import re

IGNORED_DIRS = {'.git', '__pycache__', 'node_modules', '.venv', 'venv', 'env', '.idea', '.github'}
MD_GLOBS = ['*.md', '*.markdown']


from django.utils.text import slugify as _dj_slugify


def slugify(text: str) -> str:
    """Return an ASCII-only slug using Django's slugify (allow_unicode=False).

    This ensures slugs do not contain accented characters or other non-ASCII
    letters which can break URL reversing patterns that expect [A-Za-z0-9_\-].
    """
    return _dj_slugify(text, allow_unicode=False)


def gather_markdown_files(root: Path):
    for p in root.rglob('*.md'):
        # skip ignored parts
        if any(part in IGNORED_DIRS for part in p.parts):
            continue
        yield p


def extract_title_and_description(text: str, default_title: str):
    title = None
    meta = ''
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if not title and stripped.startswith('#'):
            title = stripped.lstrip('#').strip()
        if not meta:
            meta = stripped[:160]
        if title and meta:
            break
    if not title:
        title = default_title
    return title, meta


def sql_escape(s: str) -> str:
    if s is None:
        return ''
    return s.replace("'", "''")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--root', help='Repo root to scan (defaults to repo root containing manage.py)')
    parser.add_argument('--out', help='Output SQL file', default='documentum_seed.sql')
    parser.add_argument('--dialect', choices=['sqlite', 'postgres'], default='sqlite', help='SQL dialect to generate')
    parser.add_argument('--apply', action='store_true', help='Apply the generated SQL to local sqlite db (only for sqlite dialect)')
    args = parser.parse_args()

    # detect repo root by locating manage.py
    base = Path(args.root) if args.root else Path.cwd()
    if not (base / 'manage.py').exists():
        # search upwards
        p = Path(__file__).resolve()
        repo_root = next((parent for parent in p.parents if (parent / 'manage.py').exists()), None)
        if repo_root:
            base = repo_root

    print(f'Scanning {base} for markdown files...')

    files = sorted(gather_markdown_files(base))
    if not files:
        print('No markdown files found.')
        return

    categories = {}
    inserts = []

    for md in files:
        rel = md.relative_to(base)
        parts = rel.parts
        if len(parts) > 1:
            cat_name = parts[0]
        else:
            cat_name = 'General'
        cat_slug = slugify(cat_name)
        categories.setdefault(cat_slug, cat_name)

        raw = md.read_text(encoding='utf-8')
        default_title = md.stem.replace('_', ' ').replace('-', ' ').title()
        title, meta = extract_title_and_description(raw, default_title)
        slug = slugify(title)

        content = sql_escape(raw)
        title_e = sql_escape(title)
        meta_e = sql_escape(meta)

        doc_insert = (
            "INSERT OR IGNORE INTO documentum_document "
            "(title, slug, category_id, content_markdown, content_html, status, last_revision, stack_version, meta_description, meta_keywords, created_at, updated_at)"
            f" VALUES ('{title_e}', '{slug}', (SELECT id FROM documentum_category WHERE slug='{cat_slug}'), '{content}', '', 'published', CURRENT_TIMESTAMP, '', '{meta_e}', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);"
        )
        ver_insert = (
            "INSERT OR IGNORE INTO documentum_documentversion "
            "(document_id, content_markdown, created_at, changed_by, change_summary)"
            f" VALUES ((SELECT id FROM documentum_document WHERE slug='{slug}'), '{content}', CURRENT_TIMESTAMP, 'import-script', 'Imported from {sql_escape(str(rel))}');"
        )
        inserts.append((cat_slug, doc_insert, ver_insert))

    dialect = args.dialect
    out = Path(args.out)

    def write_sql_sqlite(fh):
        fh.write('-- Generated by scripts/generate_documentum_sql.py (sqlite dialect)\n')
        fh.write('PRAGMA foreign_keys=OFF;\nBEGIN TRANSACTION;\n')
        # categories
        for slug, name in categories.items():
            name_e = sql_escape(name)
            desc_e = sql_escape(f'Imported category {name}')
            fh.write(
                f"INSERT OR IGNORE INTO documentum_category (name, slug, description, icon, \"order\", is_visible, created_at, updated_at) VALUES ('{name_e}', '{slug}', '{desc_e}', 'fa-book', 0, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);\n"
            )
        fh.write('\n')
        # documents and versions
        for cat_slug, doc_sql, ver_sql in inserts:
            fh.write(doc_sql + '\n')
            fh.write(ver_sql + '\n')
        fh.write('COMMIT;\n')

    def write_sql_postgres(fh):
        """Postgres writer is intentionally lightweight: for robust conversion we prefer using
        `convert_to_postgres.py` against the SQLite output. This keeps the code here simple
        and avoids complex parsing that can be brittle.
        """
        fh.write('-- Generated by scripts/generate_documentum_sql.py (postgres dialect - lightweight)\n')
        fh.write('BEGIN;\n')
        for slug, name in categories.items():
            name_e = sql_escape(name)
            desc_e = sql_escape(f'Imported category {name}')
            fh.write(
                f"INSERT INTO documentum_category (name, slug, description, icon, \"order\", is_visible, created_at, updated_at) VALUES ('{name_e}', '{slug}', '{desc_e}', 'fa-book', 0, true, now(), now()) ON CONFLICT (slug) DO NOTHING;\n"
            )
        fh.write('\n')
        # For documents and versions emit inserts similar to the sqlite variant but
        # replace CURRENT_TIMESTAMP with now() and remove 'INSERT OR IGNORE' usage.
        for cat_slug, doc_sql, ver_sql in inserts:
            doc_sql_p = doc_sql.replace('INSERT OR IGNORE INTO', 'INSERT INTO')
            doc_sql_p = doc_sql_p.replace('CURRENT_TIMESTAMP', 'now()')
            if doc_sql_p.strip().endswith(';'):
                doc_sql_p = doc_sql_p.strip()[:-1]
            doc_sql_p = doc_sql_p + " ON CONFLICT (slug) DO NOTHING;"
            fh.write(doc_sql_p + '\n')
            ver_sql_p = ver_sql.replace('INSERT OR IGNORE INTO', 'INSERT INTO')
            ver_sql_p = ver_sql_p.replace('CURRENT_TIMESTAMP', 'now()')
            fh.write(ver_sql_p + '\n')
        fh.write('COMMIT;\n')

    # write out file according to dialect
    with out.open('w', encoding='utf-8') as fh:
        if dialect == 'sqlite':
            write_sql_sqlite(fh)
        else:
            # For postgres we rely on simpler constructs and ON CONFLICT
            # Note: the 'inserts' tuples already contain content safely escaped
            # We'll emit inserts in a safer explicit manner for Postgres
            # To keep implementation robust, reuse the same data but craft Postgres statements
            fh.write('-- Generated by scripts/generate_documentum_sql.py (postgres dialect)\n')
            fh.write('BEGIN;\n')
            for slug, name in categories.items():
                name_e = sql_escape(name)
                desc_e = sql_escape(f'Imported category {name}')
                fh.write(f"INSERT INTO documentum_category (name, slug, description, icon, \"order\", is_visible, created_at, updated_at) VALUES ('{name_e}', '{slug}', '{desc_e}', 'fa-book', 0, true, now(), now()) ON CONFLICT (slug) DO NOTHING;\n")
            fh.write('\n')
            for cat_slug, doc_sql, ver_sql in inserts:
                # reuse doc_sql and ver_sql but convert keywords
                # replace CURRENT_TIMESTAMP with now() and INSERT OR IGNORE with ON CONFLICT
                doc_sql_p = doc_sql.replace('INSERT OR IGNORE INTO', 'INSERT INTO')
                doc_sql_p = doc_sql_p.replace('CURRENT_TIMESTAMP', 'now()')
                # change trailing ; to ON CONFLICT DO NOTHING;
                if doc_sql_p.strip().endswith(';'):
                    doc_sql_p = doc_sql_p.strip()[:-1]
                doc_sql_p = doc_sql_p + " ON CONFLICT (slug) DO NOTHING;"
                doc_sql_p = doc_sql_p.replace("(SELECT id FROM documentum_category WHERE slug='", "(SELECT id FROM documentum_category WHERE slug='")
                fh.write(doc_sql_p + '\n')
                ver_sql_p = ver_sql.replace('INSERT OR IGNORE INTO', 'INSERT INTO')
                ver_sql_p = ver_sql_p.replace('CURRENT_TIMESTAMP', 'now()')
                if ver_sql_p.strip().endswith(';'):
                    ver_sql_p = ver_sql_p.strip()
                fh.write(ver_sql_p + '\n')
            fh.write('COMMIT;\n')

    print(f'Wrote {out} with {len(inserts)} documents and {len(categories)} categories (dialect={dialect}).')

    # Optionally apply the SQL to a local sqlite DB
    if args.apply:
        if dialect != 'sqlite':
            print('Applying SQL to local DB is only supported for sqlite dialect via --apply.')
            return
        # locate db.sqlite3
        from shutil import copyfile
        repo_root = Path(__file__).resolve().parents[3]
        db_file = repo_root / 'db.sqlite3'
        if not db_file.exists():
            print(f'No local sqlite DB found at {db_file}. Aborting apply.')
            return
        backup = repo_root / 'db.sqlite3.backup'
        copyfile(db_file, backup)
        print(f'Backed up DB to {backup}')
        import sqlite3
        conn = sqlite3.connect(str(db_file))
        with open(out, 'r', encoding='utf-8') as f:
            sql_script = f.read()
        conn.executescript(sql_script)
        conn.commit()
        conn.close()
        print(f'Applied {out} to {db_file} (dialect=sqlite)')


if __name__ == '__main__':
    main()
