# Generated by Django 6.0 on 2026-02-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Infrastructure')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version (auto-generated)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('icon', models.CharField(default='fa-book', help_text="FontAwesome icon class (e.g., 'fa-server')", max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_visible', models.BooleanField(default=True, help_text='Show in public category list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version (auto-generated)', max_length=200, unique=True)),
                ('content_markdown', models.TextField(help_text='Markdown source (editable)')),
                ('content_html', models.TextField(blank=True, editable=False, help_text='Rendered HTML (auto-generated)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', help_text='Publication status', max_length=20)),
                ('last_revision', models.DateTimeField(auto_now=True, help_text='Last modification date')),
                ('stack_version', models.CharField(blank=True, help_text="Tech stack version (e.g., 'Django 5.1, Python 3.12')", max_length=100)),
                ('meta_description', models.CharField(help_text='SEO meta description (max 160 chars)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Documentation category', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documentum.category')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_markdown', models.TextField(help_text='Markdown content at this version')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Version creation timestamp')),
                ('changed_by', models.CharField(help_text='User who made the change', max_length=100)),
                ('change_summary', models.TextField(blank=True, help_text='Summary of changes made')),
                ('document', models.ForeignKey(help_text='Parent document', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documentum.document')),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', '-updated_at'], name='documentum__status_b5bc58_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category', 'status'], name='documentum__categor_1b0c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', '-created_at'], name='documentum__documen_b71d17_idx'),
        ),
    ]
