# Generated by Django 6.0 on 2026-01-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen_url',
            field=models.URLField(blank=True, help_text="Pega aquí la URL 'raw' de GitHub", max_length=500, null=True),
        ),
    ]
