# Generated by Django 6.0 on 2026-09-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_subscriber_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
