# Generated by Django 5.1.5 on 2025-02-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='nacimiento',
            field=models.CharField(default='8 de Noviembre de 1983', max_length=100),
        ),
        migrations.AddField(
            model_name='info',
            name='perfil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='skill',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='trabajo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='web',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='score',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
