# Generated by Django 5.1.5 on 2025-02-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_info_nacimiento_info_perfil_info_resumen_info_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
