# Generated by Django 5.1.5 on 2025-02-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_experience_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
