# Generated by Django 5.1.5 on 2025-06-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_project_categoria_project_imagen_project_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='porfolio_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='porfolio_subtitle',
            field=models.CharField(default='Portfolio', max_length=300),
        ),
        migrations.AddField(
            model_name='info',
            name='porfolio_title',
            field=models.CharField(default='Portfolio', max_length=150),
        ),
    ]
