# Generated by Django 5.1.5 on 2025-06-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_info_porfolio_description_info_porfolio_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Experience_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='Experience_subtitle',
            field=models.CharField(default='Experience', max_length=300),
        ),
        migrations.AddField(
            model_name='info',
            name='Experience_title',
            field=models.CharField(default='Experience', max_length=150),
        ),
    ]
