# Generated by Django 5.1.5 on 2025-07-03 16:36

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_info_experience_description_info_experience_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Experience_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Text'),
        ),
    ]
