# Generated by Django 5.1.5 on 2025-07-03 16:49

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_alter_info_experience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='resumen',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resumen',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Text'),
        ),
    ]
