# Generated by Django 6.0 on 2026-01-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='app_name',
            field=models.CharField(default='landing', help_text='Ej: landing, prompts, blog', max_length=50),
        ),
    ]
