# Generated by Django 6.0.1 on 2026-01-30 17:01

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_menuitem_app_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(help_text='Valor numérico del contador (ej: 25, 100)')),
                ('prefix', models.CharField(blank=True, default='', help_text="Prefijo opcional (ej: '+')", max_length=10)),
                ('suffix', models.CharField(blank=True, default='', help_text="Sufijo opcional (ej: '%')", max_length=10)),
                ('title', models.CharField(help_text='Título de la métrica', max_length=100)),
                ('description', models.TextField(help_text='Descripción detallada')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición (menor = primero)')),
            ],
            options={
                'verbose_name': 'Métrica de Impacto',
                'verbose_name_plural': 'Métricas de Impacto',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='education',
            name='link',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='education',
            name='resumen',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='info',
            name='Experience_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='info',
            name='perfil',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='porfolio_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='resumen',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='skill',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='trabajo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='web',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='imagen',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
