# Generated by Django 6.0.1 on 2026-01-30 17:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_metric_alter_education_link_alter_education_resumen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='resumen',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Text'),
        ),
    ]
