# Generated by Django 6.0.3 on 2026-03-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_alter_experience_resumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('logo', models.ImageField(upload_to='companies/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa Colaboradora',
                'verbose_name_plural': 'Empresas Colaboradoras',
                'ordering': ['order'],
            },
        ),
    ]
