# Generated by Django 6.0.3 on 2026-03-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_add_company_collaboration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycollaboration',
            name='logo',
            field=models.CharField(blank=True, help_text='Ejemplo: /profile/Foto_perfil2.webp. Se concatenará con BRAND_ASSETS_URL.', max_length=255, null=True, verbose_name='Ruta del Logo CDN'),
        ),
    ]
