# Generated by Django 6.0.3 on 2026-03-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_cdn_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imagen',
            field=models.CharField(blank=True, default='', help_text='Ruta CDN relativa, ej: /projects/foto.webp', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='companycollaboration',
            index=models.Index(fields=['is_active', 'order'], name='landing_com_is_acti_a178f1_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['-fecha_envio'], name='landing_con_fecha_e_23f9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['leido'], name='landing_con_leido_0a5ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['is_visible', 'order'], name='landing_met_is_visi_2792b1_idx'),
        ),
    ]
