# Generated by Django 6.0 on 2026-09-25 16:44

from django.db import migrations


def add_analytics_menu(apps, schema_editor):
    """Crear menú item de Analytics si no existe."""
    MenuItem = apps.get_model('landing', 'MenuItem')

    analytics_item, created = MenuItem.objects.get_or_create(
        title='📊 Analítica',
        defaults={
            'url_name': 'dashboard',
            'app_name': 'analytics',
            'icon': 'bi bi-bar-chart-fill',
            'order': 5,
            'is_active': True,
            'parent': None,
        }
    )

    if created:
        print(f"✓ Menú Analytics creado: {analytics_item.title}")
    else:
        print(f"✓ Menú Analytics ya existe")


def reverse_analytics_menu(apps, schema_editor):
    """Remover menú item de Analytics."""
    MenuItem = apps.get_model('landing', 'MenuItem')
    MenuItem.objects.filter(title='📊 Analítica').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_alter_project_imagen_alter_project_link_and_more'),
    ]

    operations = [
        migrations.RunPython(add_analytics_menu, reverse_analytics_menu),
    ]
