# Generated by Django 6.0 on 2026-09-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_add_analytics_menu_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden dentro de cada experiencia (menor = primero)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Stack tecnológico',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='resumen',
            field=models.CharField(blank=True, default='', help_text='Resumen de 1-2 frases para la tarjeta. Si se deja vacío se usa el inicio de la descripción.', max_length=220),
        ),
        migrations.AddField(
            model_name='experience',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='landing.technology', verbose_name='Stack tecnológico'),
        ),
    ]
