# Generated by Django 6.0 on 2026-09-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_technology_stack_project_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden en el portfolio (menor = primero)', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='project',
            name='categoria',
            field=models.CharField(blank=True, default='', help_text='Categorías separadas por comas, ej: Django, Python, Web. Se usan en el filtro.', max_length=100),
        ),
    ]
