# Generated by Django 6.0 on 2026-09-29 11:03

from django.db import migrations, models


CREDLY_PROFILE = 'https://www.credly.com/users/javier-hernandez.53ccb137/badges'


def set_credly_profile(apps, schema_editor):
    """Sin shell en producción: deja configurado el perfil (editable después en el admin)."""
    Info = apps.get_model('landing', 'Info')
    Info.objects.filter(credly_url='').update(credly_url=CREDLY_PROFILE)


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_project_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredlyBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credly_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('issuer', models.CharField(blank=True, default='', max_length=150, verbose_name='Emisor')),
                ('image_url', models.URLField(max_length=500, verbose_name='Imagen')),
                ('badge_url', models.URLField(max_length=500, verbose_name='Enlace de verificación')),
                ('issued_at', models.DateField(verbose_name='Fecha de emisión')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Caduca')),
                ('is_visible', models.BooleanField(default=True, help_text='Desmárcala para ocultarla en la web; la sincronización la respeta.', verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insignia de Credly',
                'verbose_name_plural': 'Insignias de Credly',
                'ordering': ['-issued_at', 'name'],
            },
        ),
        migrations.AddField(
            model_name='info',
            name='credly_url',
            field=models.URLField(blank=True, default='', help_text='URL pública de tus insignias, ej: https://www.credly.com/users/tu-usuario/badges. Las insignias se sincronizan en cada despliegue (comando sync_credly).', max_length=300, verbose_name='Perfil de Credly'),
        ),
        migrations.RunPython(set_credly_profile, migrations.RunPython.noop),
    ]
